{"The Beatles": ["John","Paul","George", "Ringo"],
 "The Rolling Stones":["Mick","Keith","Charlie","Ron", "Brian", "Bill", "Dick", "Ian"],
"The Who": ["Pete","Roger","Keith","John"],
"Led Zeppelin": ["Robert", "Jimmy", "John", "John Paul"],
"The Beach Boys": ["Brian", "Carl", "Dennis", "Mike", "Alan"], 
"Pink Floyd": ["Roger", "Syd"],
"Black Sabbath":["Ozzy"],
"Queen":["Freddie"],
"U2": ["Bono"],
"The Doors": ["Jim"],
"Run-D.M.C.": ["Joseph"], 
"Sly and The Family Stone": ["Sly"],
"The Grateful Dead": ["Jerry"],
"Nirvana": ["Kurt Cobain"],
"The Supremes": ["Diana Ross"],
"The Temptations": ["Otis"],
"Aerosmith": ["Steven"],
"The Police": ["Sting"],
"The Bee Gees": ["Barry", "Robin", "Maurice"]}